export interface NationalSubsidy {
  title: string;
  description: string;
  maxAmount: number;
  subsidyRate: number;
  targetAudiences: string[];
  categorySlug: string;
  requirements: string;
  sourceUrl: string;
  isNational: boolean;
  isStartupFriendly: boolean;
}

export const NATIONAL_SUBSIDIES: NationalSubsidy[] = [
  {
    title: 'IT導入補助金2024',
    description: '中小企業・小規模事業者がITツールを導入する際の費用の一部を補助します。業務効率化・売上向上に活用できます。',
    maxAmount: 4500000,
    subsidyRate: 0.5,
    targetAudiences: ['CORPORATION', 'STARTUP'],
    categorySlug: 'it',
    requirements: '中小企業・小規模事業者であること。ITツール導入の具体的な計画があること。',
    sourceUrl: 'https://www.it-hojo.jp/',
    isNational: true,
    isStartupFriendly: true,
  },
  {
    title: 'ものづくり補助金',
    description: '中小企業・小規模事業者が取り組む革新的サービス開発・試作品開発・生産プロセスの改善に必要な設備投資等を支援します。',
    maxAmount: 12500000,
    subsidyRate: 0.5,
    targetAudiences: ['CORPORATION'],
    categorySlug: 'manufacturing',
    requirements: '付加価値額年率平均3%以上増加。給与支給総額年率平均1.5%以上増加。',
    sourceUrl: 'https://portal.monodukuri-hojo.jp/',
    isNational: true,
    isStartupFriendly: false,
  },
  {
    title: '小規模事業者持続化補助金',
    description: '小規模事業者が経営計画を作成し、商工会・商工会議所の支援を受けながら取り組む販路開拓等の取組を支援します。',
    maxAmount: 2000000,
    subsidyRate: 0.667,
    targetAudiences: ['CORPORATION', 'INDIVIDUAL'],
    categorySlug: 'business',
    requirements: '小規模事業者であること。商工会・商工会議所の指導・助言を受けること。',
    sourceUrl: 'https://r3.jizokukahojokin.info/',
    isNational: true,
    isStartupFriendly: false,
  },
  {
    title: '事業再構築補助金',
    description: '新型コロナウイルス感染症の影響を受けた中小企業等が、新分野展開や業態転換、事業・業種転換等の事業再構築に取り組む場合に補助します。',
    maxAmount: 150000000,
    subsidyRate: 0.5,
    targetAudiences: ['CORPORATION', 'STARTUP'],
    categorySlug: 'business',
    requirements: '2020年4月以降の連続する6ヶ月中3ヶ月の合計売上高がコロナ以前と比較して10%以上減少。',
    sourceUrl: 'https://jigyou-saikouchiku.go.jp/',
    isNational: true,
    isStartupFriendly: true,
  },
  {
    title: '雇用調整助成金',
    description: '経済上の理由により事業活動の縮小を余儀なくされた事業主が、労働者への休業手当等を支払った場合に助成します。',
    maxAmount: 9000,
    subsidyRate: 0.75,
    targetAudiences: ['CORPORATION'],
    categorySlug: 'employment',
    requirements: '雇用保険適用事業所の事業主。売上等が前年同期比10%以上減少。',
    sourceUrl: 'https://www.mhlw.go.jp/stf/seisakunitsuite/bunya/koyou_roudou/koyou/kyufukin/pageL07.html',
    isNational: true,
    isStartupFriendly: false,
  },
  {
    title: '創業補助金（地域創業促進支援事業）',
    description: '地域の課題解決や新たな価値創造を担う創業者を支援するため、創業に必要な経費の一部を補助します。',
    maxAmount: 2000000,
    subsidyRate: 0.667,
    targetAudiences: ['STARTUP', 'INDIVIDUAL'],
    categorySlug: 'startup',
    requirements: '計画期間内に創業すること。認定市区町村や認定連携創業支援等事業者の支援を受けること。',
    sourceUrl: 'https://www.chusho.meti.go.jp/keiei/sogyo/index.html',
    isNational: true,
    isStartupFriendly: true,
  },
  {
    title: 'キャリアアップ助成金',
    description: '有期雇用労働者、短時間労働者、派遣労働者といったいわゆる非正規雇用の労働者の企業内でのキャリアアップ等を促進するため、これらの取組を実施した事業主に対して助成します。',
    maxAmount: 720000,
    subsidyRate: 1.0,
    targetAudiences: ['CORPORATION'],
    categorySlug: 'employment',
    requirements: '有期雇用労働者等を正規雇用労働者に転換または直接雇用した事業主。',
    sourceUrl: 'https://www.mhlw.go.jp/stf/seisakunitsuite/bunya/koyou_roudou/part_haken/jigyounushi/career.html',
    isNational: true,
    isStartupFriendly: false,
  },
  {
    title: '業務改善助成金',
    description: '生産性向上に資する設備投資等（機械設備、コンサルティング導入、人材育成・教育訓練等）を行うとともに、事業場内最低賃金を一定額以上引き上げた場合、その設備投資などにかかった費用の一部を助成します。',
    maxAmount: 6000000,
    subsidyRate: 0.9,
    targetAudiences: ['CORPORATION'],
    categorySlug: 'employment',
    requirements: '中小企業・小規模事業者。事業場内最低賃金と地域別最低賃金の差額が30円以内。',
    sourceUrl: 'https://www.mhlw.go.jp/stf/seisakunitsuite/bunya/koyou_roudou/roudoukijun/zigyonushi/shienjigyou/02.html',
    isNational: true,
    isStartupFriendly: false,
  },
  {
    title: '地域おこし協力隊起業・事業化支援補助金',
    description: '地域おこし協力隊の任期終了後の起業・事業化を支援するため、起業・事業化に係る経費の一部を補助します。',
    maxAmount: 1000000,
    subsidyRate: 1.0,
    targetAudiences: ['STARTUP', 'INDIVIDUAL'],
    categorySlug: 'startup',
    requirements: '地域おこし協力隊の任期を終了した者。任期終了後１年以内に起業・事業化すること。',
    sourceUrl: 'https://www.soumu.go.jp/main_sosiki/jichi_gyousei/c-gyousei/02gyosei08_03000066.html',
    isNational: true,
    isStartupFriendly: true,
  },
  {
    title: '農業次世代人材投資資金',
    description: '就農直後の農業者の定着を図るため、農業経営が確立するまでの間の所得確保を支援します。',
    maxAmount: 1500000,
    subsidyRate: 1.0,
    targetAudiences: ['FARMER', 'INDIVIDUAL'],
    categorySlug: 'agriculture',
    requirements: '独立・自営就農時の年齢が49歳以下。農業経営基盤強化促進法の認定新規就農者であること。',
    sourceUrl: 'https://www.maff.go.jp/j/new_farmer/n_syunou/reitei.html',
    isNational: true,
    isStartupFriendly: false,
  },
  {
    title: 'スマート農業技術の開発・実証・普及事業',
    description: 'ロボット技術やICT等のスマート農業技術・機械の開発・実証・普及を支援します。',
    maxAmount: 50000000,
    subsidyRate: 0.5,
    targetAudiences: ['FARMER', 'CORPORATION'],
    categorySlug: 'agriculture',
    requirements: '農業法人・農業者・農業関連企業等。スマート農業技術の実証計画があること。',
    sourceUrl: 'https://www.maff.go.jp/j/kanbo/smart/',
    isNational: true,
    isStartupFriendly: false,
  },
  {
    title: '介護施設等開設支援補助金',
    description: '介護サービス施設・事業所の開設に必要な経費の一部を補助し、地域の介護体制の整備を促進します。',
    maxAmount: 10000000,
    subsidyRate: 0.5,
    targetAudiences: ['NONPROFIT', 'CORPORATION'],
    categorySlug: 'welfare',
    requirements: '介護保険法に基づく施設・事業所の開設を予定していること。',
    sourceUrl: 'https://www.mhlw.go.jp/stf/seisakunitsuite/bunya/hukushi_kaigo/kaigo_koureisha/index.html',
    isNational: true,
    isStartupFriendly: false,
  },
  {
    title: '子育て支援員研修事業',
    description: '地域の保育や子育て支援の仕事に関心を持つ方に対して必要な知識や技術等を修得するための研修を実施します。',
    maxAmount: 500000,
    subsidyRate: 1.0,
    targetAudiences: ['NONPROFIT', 'INDIVIDUAL'],
    categorySlug: 'childcare',
    requirements: '子育て支援員研修の実施を希望する都道府県・市区町村。',
    sourceUrl: 'https://www.mhlw.go.jp/stf/seisakunitsuite/bunya/kodomo/kodomo_kosodate/index.html',
    isNational: true,
    isStartupFriendly: false,
  },
  {
    title: '住宅確保要配慮者居住支援法人支援補助金',
    description: '住宅確保要配慮者（低額所得者、被災者、高齢者、障害者等）の民間賃貸住宅への円滑な入居を支援します。',
    maxAmount: 3000000,
    subsidyRate: 0.667,
    targetAudiences: ['NONPROFIT', 'ELDERLY', 'DISABLED'],
    categorySlug: 'housing',
    requirements: '住宅確保要配慮者居住支援法人として都道府県に指定されていること。',
    sourceUrl: 'https://www.mlit.go.jp/jutakukentiku/house/jutakukentiku_house_tk3_000055.html',
    isNational: true,
    isStartupFriendly: false,
  },
  {
    title: '障害者就労施設等からの物品等の調達推進等事業',
    description: '障害者就労施設等が製造した物品の購入や提供するサービスの利用を促進するための取組を支援します。',
    maxAmount: 5000000,
    subsidyRate: 0.75,
    targetAudiences: ['NONPROFIT', 'DISABLED'],
    categorySlug: 'welfare',
    requirements: '障害者就労施設等を運営する法人であること。',
    sourceUrl: 'https://www.mhlw.go.jp/stf/seisakunitsuite/bunya/hukushi_kaigo/shougaishahukushi/index.html',
    isNational: true,
    isStartupFriendly: false,
  },
  {
    title: '地域公共交通確保維持改善事業',
    description: '地域住民の生活に不可欠な地域公共交通の確保・維持・改善のための取組を支援します。',
    maxAmount: 20000000,
    subsidyRate: 0.5,
    targetAudiences: ['CORPORATION', 'NONPROFIT'],
    categorySlug: 'infrastructure',
    requirements: '地域公共交通の確保・維持・改善に取り組む事業者または団体。',
    sourceUrl: 'https://www.mlit.go.jp/sogoseisaku/transport/sosei_transport_tk_000007.html',
    isNational: true,
    isStartupFriendly: false,
  },
  {
    title: '省エネルギー投資促進に向けた支援補助金',
    description: '工場・事業場における省エネルギーの推進を図るため、省エネルギー設備への更新を支援します。',
    maxAmount: 150000000,
    subsidyRate: 0.333,
    targetAudiences: ['CORPORATION'],
    categorySlug: 'environment',
    requirements: '省エネ法の定期報告義務事業者または中小企業等。省エネ効果が1%以上見込まれること。',
    sourceUrl: 'https://www.enecho.meti.go.jp/category/saving_and_new/saving/enterprise/support/',
    isNational: true,
    isStartupFriendly: false,
  },
  {
    title: 'ZEH支援事業',
    description: 'ZEH（ネット・ゼロ・エネルギー・ハウス）の普及加速化を目的として、ZEHの新築・改築に対して補助を行います。',
    maxAmount: 550000,
    subsidyRate: 1.0,
    targetAudiences: ['INDIVIDUAL'],
    categorySlug: 'housing',
    requirements: '新築または既築住宅へのZEH化に取り組む一般消費者。',
    sourceUrl: 'https://sii.or.jp/zeh/',
    isNational: true,
    isStartupFriendly: false,
  },
  {
    title: 'J-クレジット制度',
    description: '省エネルギー設備の導入や再生可能エネルギーの利用等によるCO2等の排出削減量や、森林経営等による吸収量をクレジットとして国が認証します。',
    maxAmount: 0,
    subsidyRate: 0,
    targetAudiences: ['CORPORATION', 'FARMER', 'NONPROFIT'],
    categorySlug: 'environment',
    requirements: '温室効果ガスの排出削減または吸収に取り組む企業・団体・農業者等。',
    sourceUrl: 'https://japancredit.go.jp/',
    isNational: true,
    isStartupFriendly: false,
  },
  {
    title: '訪日外国人消費動向調査活用支援事業',
    description: '地域の観光振興を目的として、訪日外国人旅行者の誘客に取り組む地域の事業者等を支援します。',
    maxAmount: 5000000,
    subsidyRate: 0.5,
    targetAudiences: ['CORPORATION', 'NONPROFIT'],
    categorySlug: 'tourism',
    requirements: '観光地域づくり法人（DMO）または地方公共団体と連携した取組であること。',
    sourceUrl: 'https://www.jnto.go.jp/',
    isNational: true,
    isStartupFriendly: false,
  },
  {
    title: 'インバウンド対応力強化のための受入環境整備補助金',
    description: '訪日外国人旅行者が快適に旅行できる環境を整備するため、観光案内所や宿泊施設等の多言語対応等を支援します。',
    maxAmount: 1000000,
    subsidyRate: 0.5,
    targetAudiences: ['CORPORATION', 'NONPROFIT'],
    categorySlug: 'tourism',
    requirements: '観光関連事業者。多言語対応等の具体的な整備計画があること。',
    sourceUrl: 'https://www.mlit.go.jp/kankocho/shisaku/kokusai/ukeire.html',
    isNational: true,
    isStartupFriendly: false,
  },
  {
    title: '文化芸術活動の基盤強化のための重点支援事業',
    description: '文化芸術団体の組織基盤や経営基盤の強化を支援し、公演・展示等の文化芸術活動の継続を促進します。',
    maxAmount: 30000000,
    subsidyRate: 0.5,
    targetAudiences: ['NONPROFIT'],
    categorySlug: 'culture',
    requirements: '文化芸術活動を行う法人または団体。一定規模以上の活動実績があること。',
    sourceUrl: 'https://www.bunka.go.jp/seisaku/bunka_gyosei/shokan_horei/kibankyoka/',
    isNational: true,
    isStartupFriendly: false,
  },
  {
    title: 'スポーツ振興くじ助成（toto助成）',
    description: 'スポーツ振興くじの収益を活用して、地域のスポーツ施設整備や地域スポーツの振興活動を支援します。',
    maxAmount: 100000000,
    subsidyRate: 0.5,
    targetAudiences: ['NONPROFIT', 'CORPORATION'],
    categorySlug: 'culture',
    requirements: 'スポーツ施設の整備または地域スポーツ振興活動を行う団体・法人。',
    sourceUrl: 'https://www.jpnsport.go.jp/sinko/',
    isNational: true,
    isStartupFriendly: false,
  },
  {
    title: '高齢者の安全・安心な暮らし実現事業',
    description: '地域における高齢者の見守りや生活支援活動を行う団体を支援します。',
    maxAmount: 2000000,
    subsidyRate: 0.75,
    targetAudiences: ['NONPROFIT', 'ELDERLY'],
    categorySlug: 'welfare',
    requirements: 'NPO法人、社会福祉法人等の非営利団体。高齢者支援活動の実績があること。',
    sourceUrl: 'https://www.mhlw.go.jp/stf/seisakunitsuite/bunya/hukushi_kaigo/kaigo_koureisha/index.html',
    isNational: true,
    isStartupFriendly: false,
  },
  {
    title: 'こどもの居場所づくり支援事業',
    description: 'こどもの放課後等における居場所を確保するため、放課後児童クラブ等の整備・運営を支援します。',
    maxAmount: 5000000,
    subsidyRate: 0.667,
    targetAudiences: ['NONPROFIT', 'CHILD'],
    categorySlug: 'childcare',
    requirements: '放課後児童クラブ等を運営する法人・団体。',
    sourceUrl: 'https://www.mhlw.go.jp/stf/seisakunitsuite/bunya/kodomo/kodomo_kosodate/index.html',
    isNational: true,
    isStartupFriendly: false,
  },
];
